const datos = document.getElementById('datos')
const heredofa = document.getElementById('heredofa')
const pato = document.getElementById('pato')
const personal = document.getElementById('personal')
const diag = document.getElementById('diag')
const notas = document.getElementById('notas')
const btn_datos = document.getElementById('btn-datos')
const btn_heredofa = document.getElementById('btn-heredofa')
const btn_pato = document.getElementById('btn-pato')
const btn_personal = document.getElementById('btn-personal')
const btn_diag = document.getElementById('btn-diag')
const btn_notas = document.getElementById('btn-notas')
const agregar = document.getElementById('nota-c')

btn_heredofa.addEventListener('click', function(){
    datos.setAttribute("style", "display:none;")
    heredofa.setAttribute("style", "display:flex;")
    pato.setAttribute("style", "display:none;")
    personal.setAttribute("style", "display:none;")
    diag.setAttribute("style", "display:none;")
    notas.setAttribute("style", "display:none;")
})
btn_datos.addEventListener('click', function(){
    datos.setAttribute("style", "display:flex;")
    heredofa.setAttribute("style", "display:none;")
    pato.setAttribute("style", "display:none;")
    personal.setAttribute("style", "display:none;")
    diag.setAttribute("style", "display:none;")
    notas.setAttribute("style", "display:none;")
})
btn_pato.addEventListener('click', function(){
    datos.setAttribute("style", "display:none;")
    heredofa.setAttribute("style", "display:none;")
    pato.setAttribute("style", "display:flex;")
    personal.setAttribute("style", "display:none;")
    diag.setAttribute("style", "display:none;")
    notas.setAttribute("style", "display:none;")
})
btn_personal.addEventListener('click', function(){
    datos.setAttribute("style", "display:none;")
    heredofa.setAttribute("style", "display:none;")
    pato.setAttribute("style", "display:none;")
    personal.setAttribute("style", "display:flex;")
    diag.setAttribute("style", "display:none;")
    notas.setAttribute("style", "display:none;")
})
btn_diag.addEventListener('click', function(){
    datos.setAttribute("style", "display:none;")
    heredofa.setAttribute("style", "display:none;")
    pato.setAttribute("style", "display:none;")
    personal.setAttribute("style", "display:none;")
    diag.setAttribute("style", "display:flex;")
    notas.setAttribute("style", "display:none;")
})
btn_notas.addEventListener('click', function(){
    datos.setAttribute("style", "display:none;")
    heredofa.setAttribute("style", "display:none;")
    pato.setAttribute("style", "display:none;")
    personal.setAttribute("style", "display:none;")
    diag.setAttribute("style", "display:none;")
    notas.setAttribute("style", "display:flex;")
    agregar.setAttribute("style", "display:flex;")
})

const nota_n = document.getElementById('nota-c')
const form_n = document.getElementById('con-fnota')
const cancelar = document.getElementById('x')

nota_n.addEventListener('click', function() {
    form_n.setAttribute("style", "display:flex;")
})
cancelar.addEventListener('click', function() {
    form_n.setAttribute("style", "display:none;")
})